config/routes.rb
Rails.application.routes.draw do
  resources :todos
  
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  get '/todos/ascompleted/:id', to: 'todos#ascompleted', as: 'ascompleted'
  root 'todos#index'
  get '/hello', to: 'todos#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, :description, :due_date, :priority, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :user_login?

  def user_login?
    if not current_user
      redirect_to("/users/sign_in")
    end
  end
end

app/controllers/todos_controller.rb
class TodosController < BaseController
  def index
    @todos = Todo.where(user_id: current_user.id)
  end

  def show
    @todo = Todo.where(user_id: current_user.id).find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = current_user.id

    if @todo.save
      redirect_to @todo
    else
      render 'new'
    end
  end

  def edit
    @todo = Todo.where(user_id: current_user.id).find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.user_id = current_user.id
   
    if @todo.update(todo_params)
      redirect_to @todo
    else
      render 'edit'
    end
  end

  def destroy
    @todo = Todo.where(user_id: current_user.id).find(params[:id])
    @todo.destroy

    redirect_to todos_path
  end

  def ascompleted
    @todo = Todo.where(user_id: current_user.id).find(params[:id])
    @todo.is_completed = params[:status]
    @todo.completed_at = DateTime.now.to_date
    @todo.save

    redirect_to todos_path
  end

  private
    def todo_params
      params.require(:todo).permit(:name, :description, :due_date, :priority, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title To Do List App
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css", :integrity => "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm", :rel => "stylesheet"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      %nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
        %a.navbar-brand{:href => "#"} Todo List App
        %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarNav.collapse.navbar-collapse
          %ul.navbar-nav
            %li.nav-item.active
              %a.nav-link{:href => "/"}
                Home
                %span.sr-only (current)
            - if user_signed_in?
              %li.nav-item
                %a.nav-link{:href => "/users/sign_out"} Logout
              %li.nav-item{:style => "float:left; margin-left:30px"}
                %a.nav-link{:href => "#", :style => "color:white;"}
                  Welcome #{current_user.email}
      = yield
    %script{:src => "//code.jquery.com/jquery-3.3.1.js"}
    %script{:src => "//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"}
    %script{:src => "//cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q", :src => "//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl", :src => "//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"}
    :javascript
      $(document).ready(function() {
          $('#todolisting').DataTable();
      } );

app/views/todos/_form.haml
.container
  = form_for @todo do |f|
    - if @todo.errors.any?
      #error_explanation
        .alert.alert-danger.sm
          %p= "#{pluralize(@todo.errors.count, 'error')} prohibited this Todo from being saved:"
          %ul.alert.alert-danger
            - @todo.errors.full_messages.each do |msg|
              %li= msg
  
    .form-group
      %label Name
      = f.text_field :name, class: 'form-control'
    .form-group
      %label Description
      = f.text_area :description, class: 'form-control'      
    %p
      %label Due Date 
      %br
      = f.date_field :due_date
    %p
      %label Priority
      %br
      = select_tag 'todo[priority]', options_for_select([['------', ''], ['High', 1], ['Medium', 2], ['Low', 3]], @todo.priority), class: 'form-control'
    %p
      = f.submit 'Save', class: 'btn btn-primary'

app/views/todos/edit.haml
.container
  %h1 Edit To Do
  = link_to '<< Back', todos_path
  = render 'form'

app/views/todos/index.haml
.container
  %h1 To Do List
  %p= link_to 'Create', new_todo_path, class: 'btn btn-primary'
  .table-responsive-md
    %table.table.table-striped.table-bordered#todolisting
      %thead
        %tr
          %th Name
          %th Priority
          %th Due Date
          %th Is Complete
          %th #

      %tbody
        - @todos.each do |todo|
          %tr
            %td= todo.name
            %td{'data-order' => todo.priority}
              - if todo.priority == 1
                High
              - elsif todo.priority == 2
                Medium
              - elsif todo.priority == 3
                Low
              - else
                Undefined
            %td= todo.due_date.strftime("%Y-%m-%d")
            %td{'data-order' => todo.is_completed}
              - if todo.is_completed
                Yes
              - else
                No
            %td
              - if todo.is_completed
                = link_to 'Uncompleted', ascompleted_path(:id=>todo.id, :status=>false), :class => 'btn btn-light btn-sm'
              - else
                = link_to 'Completed', ascompleted_path(:id=>todo.id, :status=>true), :class=>'btn btn-light btn-sm'
              = link_to 'Edit', edit_todo_path(todo), :class=>'btn btn-light btn-sm'
              = link_to 'Show', todo_path(todo), :class=>'btn btn-light btn-sm'
              = link_to 'Delete', todo_path(todo), method: :delete, data: { confirm: 'Are you sure to delete?' }, :class=>'btn btn-danger btn-sm'

app/views/todos/new.haml
.container
  %h1
    Create To Do
  = link_to '<< Back', todos_path
  = render 'form'

app/views/todos/show.html.haml
.container
  %h1
    Detail #{@todo.name}
  = link_to '<< Back', todos_path
  .table-responsive-md
    %table.table.table-striped
      %tr
        %th Name
        %td= @todo.name
      %tr
        %th Description
        %td= @todo.description
      %tr
        %th Due Date
        %td
          = @todo.due_date.strftime("%Y-%m-%d")
      %tr
        %th Priority
        %td
          - if @todo.priority == 1
            High
          - elsif @todo.priority == 2
            Medium
          - elsif @todo.priority == 3
            Low
          - else
            Undefined
      %tr
        %th Completed
        %td
          - if @todo.is_completed
            Yes
          - else
            No
      %tr
        %th Completed Date
        %td
          = @todo.completed_at ? @todo.completed_at.strftime("%Y-%m-%d") : ''
      %tr
        %th Created
        %td= @todo.created_at
      %tr
        %th Updated
        %td= @todo.updated_at